/* This file is generated by scripts/docs/extract-locales.mjs. */

export const milestoneConfidenceProgress = {
  "updatedAt": "2026-04-18T13:56:06.921Z",
  "trackedRuns": 5,
  "passedRuns": 5,
  "failedRuns": 0,
  "consecutivePasses": 5,
  "readiness": {
    "readinessVersion": "0.1.0",
    "status": "building-history",
    "requiredRef": "refs/heads/main",
    "qualifiedEvents": [
      "push",
      "workflow_dispatch",
      "schedule"
    ],
    "minimumQualifiedRuns": 7,
    "minimumConsecutivePasses": 3,
    "qualifiedRuns": 1,
    "qualifiedPasses": 1,
    "qualifiedFailures": 0,
    "qualifiedConsecutivePasses": 1,
    "remainingQualifiedRuns": 6,
    "remainingConsecutivePasses": 2
  },
  "visibility": {
    "qualifiedRuns": 1,
    "visibilityOnlyRuns": 4,
    "localVisibilityOnlyRuns": 4,
    "nonQualifiedRemoteRuns": 0
  },
  "latestRun": {
    "id": "2026-04-18T13:56:06.921Z-local-0",
    "outcome": "passed",
    "qualifiedForReadiness": false,
    "completedAt": "2026-04-18T13:56:06.921Z",
    "durationSeconds": 55.384,
    "failedStepName": null,
    "context": {
      "eventName": "local",
      "ref": null,
      "sha": null,
      "runId": null,
      "runAttempt": null,
      "workflow": "local"
    }
  },
  "latestQualifiedRun": {
    "id": "2026-04-18T02:38:43.991Z-24595022905-1",
    "outcome": "passed",
    "qualifiedForReadiness": true,
    "completedAt": "2026-04-18T02:38:43.991Z",
    "durationSeconds": 41.196,
    "failedStepName": null,
    "context": {
      "eventName": "push",
      "ref": "refs/heads/main",
      "sha": "a5075a78c6f40ef27cf123c2a2e559c5044d6936",
      "runId": "24595022905",
      "runAttempt": "1",
      "workflow": "mainline-acceptance"
    }
  },
  "recentRuns": [
    {
      "id": "2026-04-18T13:56:06.921Z-local-0",
      "outcome": "passed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T13:56:06.921Z",
      "durationSeconds": 55.384,
      "failedStepName": null,
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T06:14:08.370Z-local-0",
      "outcome": "passed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T06:14:08.370Z",
      "durationSeconds": 54.333,
      "failedStepName": null,
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T05:06:49.472Z-local-0",
      "outcome": "passed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T05:06:49.472Z",
      "durationSeconds": 54.282,
      "failedStepName": null,
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T04:54:47.578Z-local-0",
      "outcome": "passed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T04:54:47.578Z",
      "durationSeconds": 54.227,
      "failedStepName": null,
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T02:38:43.991Z-24595022905-1",
      "outcome": "passed",
      "qualifiedForReadiness": true,
      "completedAt": "2026-04-18T02:38:43.991Z",
      "durationSeconds": 41.196,
      "failedStepName": null,
      "context": {
        "eventName": "push",
        "ref": "refs/heads/main",
        "sha": "a5075a78c6f40ef27cf123c2a2e559c5044d6936",
        "runId": "24595022905",
        "runAttempt": "1",
        "workflow": "mainline-acceptance"
      }
    }
  ],
  "sourceFiles": {
    "historyPath": ".portmanager/reports/milestone-confidence-history.json",
    "summaryPath": ".portmanager/reports/milestone-confidence-summary.md",
    "reportPath": ".portmanager/reports/milestone-confidence-report.json"
  },
  "publication": {
    "trackedDataPath": "docs-site/data/milestone-confidence-progress.ts",
    "defaultMode": "reuse-committed-artifact",
    "explicitRefreshFlag": "--refresh-confidence-progress",
    "refreshCommand": "pnpm --dir docs-site --ignore-workspace run docs:generate:refresh-confidence"
  }
} as const
