/* This file is generated by scripts/docs/extract-locales.mjs. */

export const milestoneConfidenceProgress = {
  "updatedAt": "2026-04-21T01:42:16.756Z",
  "trackedRuns": 19,
  "passedRuns": 18,
  "failedRuns": 1,
  "consecutivePasses": 16,
  "readiness": {
    "readinessVersion": "0.1.0",
    "status": "promotion-ready",
    "requiredRef": "refs/heads/main",
    "qualifiedEvents": [
      "push",
      "workflow_dispatch",
      "schedule"
    ],
    "minimumQualifiedRuns": 7,
    "minimumConsecutivePasses": 3,
    "qualifiedRuns": 13,
    "qualifiedPasses": 13,
    "qualifiedFailures": 0,
    "qualifiedConsecutivePasses": 13,
    "remainingQualifiedRuns": 0,
    "remainingConsecutivePasses": 0
  },
  "visibility": {
    "qualifiedRuns": 13,
    "visibilityOnlyRuns": 6,
    "localVisibilityOnlyRuns": 6,
    "nonQualifiedRemoteRuns": 0
  },
  "latestRun": {
    "id": "2026-04-21T01:42:16.756Z-24699564258-1",
    "outcome": "passed",
    "qualifiedForReadiness": true,
    "completedAt": "2026-04-21T01:42:16.756Z",
    "durationSeconds": 41.242,
    "failedStepName": null,
    "context": {
      "eventName": "push",
      "ref": "refs/heads/main",
      "sha": "d11cd001ae31b6f5be47cf07c497309943e36176",
      "runId": "24699564258",
      "runAttempt": "1",
      "workflow": "mainline-acceptance"
    }
  },
  "latestQualifiedRun": {
    "id": "2026-04-21T01:42:16.756Z-24699564258-1",
    "outcome": "passed",
    "qualifiedForReadiness": true,
    "completedAt": "2026-04-21T01:42:16.756Z",
    "durationSeconds": 41.242,
    "failedStepName": null,
    "context": {
      "eventName": "push",
      "ref": "refs/heads/main",
      "sha": "d11cd001ae31b6f5be47cf07c497309943e36176",
      "runId": "24699564258",
      "runAttempt": "1",
      "workflow": "mainline-acceptance"
    }
  },
  "recentRuns": [
    {
      "id": "2026-04-21T01:42:16.756Z-24699564258-1",
      "outcome": "passed",
      "qualifiedForReadiness": true,
      "completedAt": "2026-04-21T01:42:16.756Z",
      "durationSeconds": 41.242,
      "failedStepName": null,
      "context": {
        "eventName": "push",
        "ref": "refs/heads/main",
        "sha": "d11cd001ae31b6f5be47cf07c497309943e36176",
        "runId": "24699564258",
        "runAttempt": "1",
        "workflow": "mainline-acceptance"
      }
    },
    {
      "id": "2026-04-21T01:33:43.736Z-24699338529-1",
      "outcome": "passed",
      "qualifiedForReadiness": true,
      "completedAt": "2026-04-21T01:33:43.736Z",
      "durationSeconds": 41.067,
      "failedStepName": null,
      "context": {
        "eventName": "push",
        "ref": "refs/heads/main",
        "sha": "9e0fd4c8c0eeb0e0ddd0b271d21889654f34d74c",
        "runId": "24699338529",
        "runAttempt": "1",
        "workflow": "mainline-acceptance"
      }
    },
    {
      "id": "2026-04-20T05:59:53.816Z-24650868231-1",
      "outcome": "passed",
      "qualifiedForReadiness": true,
      "completedAt": "2026-04-20T05:59:53.816Z",
      "durationSeconds": 42.739,
      "failedStepName": null,
      "context": {
        "eventName": "schedule",
        "ref": "refs/heads/main",
        "sha": "d7b90cdcba4ffdd24abdaf6e3b0c7cc807403d44",
        "runId": "24650868231",
        "runAttempt": "1",
        "workflow": "mainline-acceptance"
      }
    },
    {
      "id": "2026-04-20T04:48:51.071Z-24648911705-1",
      "outcome": "passed",
      "qualifiedForReadiness": true,
      "completedAt": "2026-04-20T04:48:51.071Z",
      "durationSeconds": 42.13,
      "failedStepName": null,
      "context": {
        "eventName": "push",
        "ref": "refs/heads/main",
        "sha": "d7b90cdcba4ffdd24abdaf6e3b0c7cc807403d44",
        "runId": "24648911705",
        "runAttempt": "1",
        "workflow": "mainline-acceptance"
      }
    },
    {
      "id": "2026-04-20T04:33:37.986Z-24648519364-1",
      "outcome": "passed",
      "qualifiedForReadiness": true,
      "completedAt": "2026-04-20T04:33:37.986Z",
      "durationSeconds": 41.278,
      "failedStepName": null,
      "context": {
        "eventName": "push",
        "ref": "refs/heads/main",
        "sha": "1a53f5ab59755e7be27bbdcfaf05ac44a11c67fa",
        "runId": "24648519364",
        "runAttempt": "1",
        "workflow": "mainline-acceptance"
      }
    },
    {
      "id": "2026-04-20T04:17:14.570Z-24648118236-1",
      "outcome": "passed",
      "qualifiedForReadiness": true,
      "completedAt": "2026-04-20T04:17:14.570Z",
      "durationSeconds": 40.597,
      "failedStepName": null,
      "context": {
        "eventName": "push",
        "ref": "refs/heads/main",
        "sha": "40780ac3b28358ec916699fdceee82c4fff26d4b",
        "runId": "24648118236",
        "runAttempt": "1",
        "workflow": "mainline-acceptance"
      }
    }
  ],
  "sourceFiles": {
    "historyPath": ".portmanager/reports/milestone-confidence-history.json",
    "summaryPath": ".portmanager/reports/milestone-confidence-summary.md",
    "reportPath": ".portmanager/reports/milestone-confidence-report.json"
  },
  "publication": {
    "trackedDataPath": "docs-site/data/milestone-confidence-progress.ts",
    "defaultMode": "reuse-committed-artifact",
    "explicitRefreshFlag": "--refresh-confidence-progress",
    "refreshCommand": "pnpm --dir docs-site --ignore-workspace run docs:generate:refresh-confidence"
  }
} as const
