/* This file is generated by scripts/docs/extract-locales.mjs. */

export const milestoneConfidenceProgress = {
  "updatedAt": "2026-04-18T04:12:02.957Z",
  "trackedRuns": 7,
  "passedRuns": 6,
  "failedRuns": 1,
  "consecutivePasses": 4,
  "readiness": {
    "readinessVersion": "0.1.0",
    "status": "building-history",
    "requiredRef": "refs/heads/main",
    "qualifiedEvents": [
      "push",
      "workflow_dispatch",
      "schedule"
    ],
    "minimumQualifiedRuns": 7,
    "minimumConsecutivePasses": 3,
    "qualifiedRuns": 1,
    "qualifiedPasses": 1,
    "qualifiedFailures": 0,
    "qualifiedConsecutivePasses": 1,
    "remainingQualifiedRuns": 6,
    "remainingConsecutivePasses": 2
  },
  "visibility": {
    "qualifiedRuns": 1,
    "visibilityOnlyRuns": 6,
    "localVisibilityOnlyRuns": 6,
    "nonQualifiedRemoteRuns": 0
  },
  "latestRun": {
    "id": "2026-04-18T04:12:02.957Z-local-0",
    "outcome": "passed",
    "qualifiedForReadiness": false,
    "completedAt": "2026-04-18T04:12:02.957Z",
    "durationSeconds": 18.85,
    "failedStepName": null,
    "context": {
      "eventName": "local",
      "ref": null,
      "sha": null,
      "runId": null,
      "runAttempt": null,
      "workflow": "local"
    }
  },
  "latestQualifiedRun": {
    "id": "2026-04-18T02:38:43.991Z-24595022905-1",
    "outcome": "passed",
    "qualifiedForReadiness": true,
    "completedAt": "2026-04-18T02:38:43.991Z",
    "durationSeconds": 41.196,
    "failedStepName": null,
    "context": {
      "eventName": "push",
      "ref": "refs/heads/main",
      "sha": "a5075a78c6f40ef27cf123c2a2e559c5044d6936",
      "runId": "24595022905",
      "runAttempt": "1",
      "workflow": "mainline-acceptance"
    }
  },
  "recentRuns": [
    {
      "id": "2026-04-18T04:12:02.957Z-local-0",
      "outcome": "passed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T04:12:02.957Z",
      "durationSeconds": 18.85,
      "failedStepName": null,
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T03:46:57.964Z-local-0",
      "outcome": "passed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T03:46:57.964Z",
      "durationSeconds": 18.911,
      "failedStepName": null,
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T03:25:23.956Z-local-0",
      "outcome": "passed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T03:25:23.956Z",
      "durationSeconds": 18.845,
      "failedStepName": null,
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T02:56:35.102Z-local-0",
      "outcome": "passed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T02:56:35.102Z",
      "durationSeconds": 18.894,
      "failedStepName": null,
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T02:55:36.951Z-local-0",
      "outcome": "failed",
      "qualifiedForReadiness": false,
      "completedAt": "2026-04-18T02:55:36.951Z",
      "durationSeconds": 17.445,
      "failedStepName": "Build docs-site publishing layer",
      "context": {
        "eventName": "local",
        "ref": null,
        "sha": null,
        "runId": null,
        "runAttempt": null,
        "workflow": "local"
      }
    },
    {
      "id": "2026-04-18T02:38:43.991Z-24595022905-1",
      "outcome": "passed",
      "qualifiedForReadiness": true,
      "completedAt": "2026-04-18T02:38:43.991Z",
      "durationSeconds": 41.196,
      "failedStepName": null,
      "context": {
        "eventName": "push",
        "ref": "refs/heads/main",
        "sha": "a5075a78c6f40ef27cf123c2a2e559c5044d6936",
        "runId": "24595022905",
        "runAttempt": "1",
        "workflow": "mainline-acceptance"
      }
    }
  ],
  "sourceFiles": {
    "historyPath": ".portmanager/reports/milestone-confidence-history.json",
    "summaryPath": ".portmanager/reports/milestone-confidence-summary.md",
    "reportPath": ".portmanager/reports/milestone-confidence-report.json"
  }
} as const
